app:
  name: ui
  image:
    repository: 'onecx/onecx-bookmark-ui'
  routing:
    enabled: true
    path: /mfe/bookmark/
  operator:
    # Microfrontend
    microfrontend:
      enabled: true
      specs:
        main:
          exposedModule: './OneCXBookmarkModule'
          description: 'OneCX Bookmark UI'
          note: 'OneCX Bookmark UI auto import via MF operator'
          type: MODULE
          technology: WEBCOMPONENTMODULE
          remoteName: onecx-bookmark
          tagName: ocx-bookmark-component
        manage-bookmark:
          exposedModule: "./OneCXManageBookmarkComponent"
          description: "Create and Delete User Bookmarks"
          type: COMPONENT
          technology: WEBCOMPONENTMODULE
          remoteName: onecx-bookmark
          tagName: ocx-manage-bookmark-component
    # Permission
    permission:
      enabled: true
      spec:
        permissions:
          BOOKMARK:
            CREATE: 'Create bookmarks'
            EDIT: 'Edit bookmarks'
            DELETE: 'Delete bookmarks'
            IMPORT: 'Import bookmarks'
            EXPORT: 'Export bookmarks'
            VIEW: 'View mode for bookmarks'
    
